# coding: utf-8

import re  # noqa: F401
import warnings  # noqa: F401

from aspose_barcode_cloud.api_client import ApiClient


class GenerateApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/OpenAPITools/openapi-generator
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def barcode_generate_barcode_type_get(
        self,
        barcode_type,
        data_type,
        data,
        image_format=None,
        two_d_display_text=None,
        text_location=None,
        text_alignment=None,
        foreground_color=None,
        background_color=None,
        units=None,
        resolution=None,
        image_height=None,
        image_width=None,
        rotation_angle=None,
        async_req=False,
        **kwargs
    ):
        """Generate barcode using GET request with parameters in route and query string.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = GenerateApi().barcode_generate_barcode_type_get(barcode_type, data_type, data, async_req=True)
        >>> result = thread.get()

        :param EncodeBarcodeType barcode_type: Type of barcode to generate. # noqa: E501
        :param EncodeDataType data_type: Type of data to encode. # noqa: E501
        :param str data: String represents data to encode # noqa: E501
        :param AvailableBarCodeImageFormat image_format: Barcode output image format.  Default value: png # noqa: E501
        :param str two_d_display_text: Text that will be displayed instead of codetext in 2D barcodes.  Used for: Aztec, Pdf417, DataMatrix, QR, MaxiCode, DotCode # noqa: E501
        :param CodeLocation text_location: Specify the displaying Text Location, set to CodeLocation.None to hide CodeText.  Default value: CodeLocation.Below. # noqa: E501
        :param TextAlignment text_alignment: Text alignment.  Default value: TextAligment.Left # noqa: E501
        :param str foreground_color: Specify the displaying bars and content Color.   Value: Color name from https://reference.aspose.com/drawing/net/system.drawing/color/ or ARGB value started with #.   For example: Color.AliceBlue or #FF000000  Default value: Color.Black. # noqa: E501
        :param str background_color: Background color of the barcode image.  Value: Color name from https://reference.aspose.com/drawing/net/system.drawing/color/ or ARGB value started with #.   For example: Color.AliceBlue or #FF000000  Default value: Color.White. # noqa: E501
        :param AvailableGraphicsUnit units: Common Units for all measuring in query. Default units: pixel. # noqa: E501
        :param float resolution: Resolution of the BarCode image.  One value for both dimensions.  Default value: 96 dpi. # noqa: E501
        :param float image_height: Height of the barcode image in given units. Default units: pixel. # noqa: E501
        :param float image_width: Width of the barcode image in given units. Default units: pixel. # noqa: E501
        :param int rotation_angle: BarCode image rotation angle, measured in degree, e.g. RotationAngle = 0 or RotationAngle = 360 means no rotation.  If RotationAngle NOT equal to 90, 180, 270 or 0, it may increase the difficulty for the scanner to read the image.  Default value: 0. # noqa: E501
        :param async_req bool
        :return: bytearray
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if async_req:
            return self.barcode_generate_barcode_type_get_with_http_info(
                barcode_type,
                data_type,
                data,
                image_format=image_format,
                two_d_display_text=two_d_display_text,
                text_location=text_location,
                text_alignment=text_alignment,
                foreground_color=foreground_color,
                background_color=background_color,
                units=units,
                resolution=resolution,
                image_height=image_height,
                image_width=image_width,
                rotation_angle=rotation_angle,
                **kwargs
            )
        else:
            (data) = self.barcode_generate_barcode_type_get_with_http_info(
                barcode_type,
                data_type,
                data,
                image_format=image_format,
                two_d_display_text=two_d_display_text,
                text_location=text_location,
                text_alignment=text_alignment,
                foreground_color=foreground_color,
                background_color=background_color,
                units=units,
                resolution=resolution,
                image_height=image_height,
                image_width=image_width,
                rotation_angle=rotation_angle,
                **kwargs
            )
            return data

    def barcode_generate_barcode_type_get_with_http_info(self, barcode_type, data_type, data, **kwargs):
        """Generate barcode using GET request with parameters in route and query string.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = GenerateApi().barcode_generate_barcode_type_get_with_http_info(barcode_type, data_type, data, async_req=True)
        >>> result = thread.get()

        :param EncodeBarcodeType barcode_type: Type of barcode to generate. # noqa: E501
        :param EncodeDataType data_type: Type of data to encode. # noqa: E501
        :param str data: String represents data to encode # noqa: E501
        :return: bytearray
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = {
            "barcode_type",
            "data_type",
            "data",
            "image_format",
            "two_d_display_text",
            "text_location",
            "text_alignment",
            "foreground_color",
            "background_color",
            "units",
            "resolution",
            "image_height",
            "image_width",
            "rotation_angle",
        }
        all_params.add("async_req")
        all_params.add("_return_http_data_only")
        all_params.add("_preload_content")
        all_params.add("_request_timeout")

        params = locals()
        for key, val in params["kwargs"].items():
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'" " to method barcode_generate_barcode_type_get" % key
                )
            if val is None:
                continue

            params[key] = val
        del params["kwargs"]
        # verify the required parameter "barcode_type" is set
        if "barcode_type" not in params or params["barcode_type"] is None:
            raise ValueError(
                "Missing the required parameter 'barcode_type' when calling 'barcode_generate_barcode_type_get'"
            )
        # verify the required parameter "data_type" is set
        if "data_type" not in params or params["data_type"] is None:
            raise ValueError(
                "Missing the required parameter 'data_type' when calling 'barcode_generate_barcode_type_get'"
            )
        # verify the required parameter "data" is set
        if "data" not in params or params["data"] is None:
            raise ValueError("Missing the required parameter 'data' when calling 'barcode_generate_barcode_type_get'")

        collection_formats = {}

        path_params = {}
        if "barcode_type" in params:
            path_params["barcodeType"] = params["barcode_type"]

        query_params = []
        if "data_type" in params:
            query_params.append(("DataType", params["data_type"]))
        if "data" in params:
            query_params.append(("Data", params["data"]))
        if "image_format" in params:
            query_params.append(("ImageFormat", params["image_format"]))
        if "two_d_display_text" in params:
            query_params.append(("TwoDDisplayText", params["two_d_display_text"]))
        if "text_location" in params:
            query_params.append(("TextLocation", params["text_location"]))
        if "text_alignment" in params:
            query_params.append(("TextAlignment", params["text_alignment"]))
        if "foreground_color" in params:
            query_params.append(("ForegroundColor", params["foreground_color"]))
        if "background_color" in params:
            query_params.append(("BackgroundColor", params["background_color"]))
        if "units" in params:
            query_params.append(("Units", params["units"]))
        if "resolution" in params:
            query_params.append(("Resolution", params["resolution"]))
        if "image_height" in params:
            query_params.append(("ImageHeight", params["image_height"]))
        if "image_width" in params:
            query_params.append(("ImageWidth", params["image_width"]))
        if "rotation_angle" in params:
            query_params.append(("RotationAngle", params["rotation_angle"]))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header "Accept"
        header_params["Accept"] = self.api_client.select_header_accept(
            [
                "image/png",
                "image/bmp",
                "image/gif",
                "image/jpeg",
                "image/svg+xml",
                "image/tiff",
                "application/json",
                "application/xml",
            ]
        )

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(
            "/barcode/generate/{barcodeType}",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="bytearray",
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", False),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def barcode_generate_body_post(self, generate_params, async_req=False, **kwargs):
        """Generate barcode using POST request with parameters in body in json or xml format.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = GenerateApi().barcode_generate_body_post(generate_params, async_req=True)
        >>> result = thread.get()

        :param GenerateParams generate_params: Parameters of generation # noqa: E501
        :param async_req bool
        :return: bytearray
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if async_req:
            return self.barcode_generate_body_post_with_http_info(generate_params, **kwargs)
        else:
            (data) = self.barcode_generate_body_post_with_http_info(generate_params, **kwargs)
            return data

    def barcode_generate_body_post_with_http_info(self, generate_params, **kwargs):
        """Generate barcode using POST request with parameters in body in json or xml format.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = GenerateApi().barcode_generate_body_post_with_http_info(generate_params, async_req=True)
        >>> result = thread.get()

        :param GenerateParams generate_params: Parameters of generation # noqa: E501
        :return: bytearray
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = {"generate_params"}
        all_params.add("async_req")
        all_params.add("_return_http_data_only")
        all_params.add("_preload_content")
        all_params.add("_request_timeout")

        params = locals()
        for key, val in params["kwargs"].items():
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method barcode_generate_body_post" % key)
            if val is None:
                continue

            params[key] = val
        del params["kwargs"]
        # verify the required parameter "generate_params" is set
        if "generate_params" not in params or params["generate_params"] is None:
            raise ValueError(
                "Missing the required parameter 'generate_params' when calling 'barcode_generate_body_post'"
            )

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if "generate_params" in params:
            body_params = params["generate_params"]
        # HTTP header "Accept"
        header_params["Accept"] = self.api_client.select_header_accept(
            [
                "image/png",
                "image/bmp",
                "image/gif",
                "image/jpeg",
                "image/svg+xml",
                "image/tiff",
                "application/json",
                "application/xml",
            ]
        )

        # HTTP header "Content-Type"
        header_params["Content-Type"] = self.api_client.select_header_content_type(
            ["application/json", "application/xml"]
        )

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(
            "/barcode/generate-body",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="bytearray",
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", False),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def barcode_generate_form_post(
        self,
        barcode_type,
        data_type,
        data,
        image_format=None,
        two_d_display_text=None,
        text_location=None,
        text_alignment=None,
        foreground_color=None,
        background_color=None,
        units=None,
        resolution=None,
        image_height=None,
        image_width=None,
        rotation_angle=None,
        async_req=False,
        **kwargs
    ):
        """Generate barcode using POST request with parameters in url ecncoded form.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = GenerateApi().barcode_generate_form_post(barcode_type, data_type, data, async_req=True)
        >>> result = thread.get()

        :param EncodeBarcodeType barcode_type: # noqa: E501
        :param EncodeDataType data_type: # noqa: E501
        :param str data: String represents data to encode # noqa: E501
        :param AvailableBarCodeImageFormat image_format: # noqa: E501
        :param str two_d_display_text: Text that will be displayed instead of codetext in 2D barcodes.  Used for: Aztec, Pdf417, DataMatrix, QR, MaxiCode, DotCode # noqa: E501
        :param CodeLocation text_location: # noqa: E501
        :param TextAlignment text_alignment: # noqa: E501
        :param str foreground_color: Specify the displaying bars and content Color.   Value: Color name from https://reference.aspose.com/drawing/net/system.drawing/color/ or ARGB value started with #.   For example: Color.AliceBlue or #FF000000  Default value: Color.Black. # noqa: E501
        :param str background_color: Background color of the barcode image.  Value: Color name from https://reference.aspose.com/drawing/net/system.drawing/color/ or ARGB value started with #.   For example: Color.AliceBlue or #FF000000  Default value: Color.White. # noqa: E501
        :param AvailableGraphicsUnit units: # noqa: E501
        :param float resolution: Resolution of the BarCode image.  One value for both dimensions.  Default value: 96 dpi. # noqa: E501
        :param float image_height: Height of the barcode image in given units. Default units: pixel. # noqa: E501
        :param float image_width: Width of the barcode image in given units. Default units: pixel. # noqa: E501
        :param int rotation_angle: BarCode image rotation angle, measured in degree, e.g. RotationAngle = 0 or RotationAngle = 360 means no rotation.  If RotationAngle NOT equal to 90, 180, 270 or 0, it may increase the difficulty for the scanner to read the image.  Default value: 0. # noqa: E501
        :param async_req bool
        :return: bytearray
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if async_req:
            return self.barcode_generate_form_post_with_http_info(
                barcode_type,
                data_type,
                data,
                image_format=image_format,
                two_d_display_text=two_d_display_text,
                text_location=text_location,
                text_alignment=text_alignment,
                foreground_color=foreground_color,
                background_color=background_color,
                units=units,
                resolution=resolution,
                image_height=image_height,
                image_width=image_width,
                rotation_angle=rotation_angle,
                **kwargs
            )
        else:
            (data) = self.barcode_generate_form_post_with_http_info(
                barcode_type,
                data_type,
                data,
                image_format=image_format,
                two_d_display_text=two_d_display_text,
                text_location=text_location,
                text_alignment=text_alignment,
                foreground_color=foreground_color,
                background_color=background_color,
                units=units,
                resolution=resolution,
                image_height=image_height,
                image_width=image_width,
                rotation_angle=rotation_angle,
                **kwargs
            )
            return data

    def barcode_generate_form_post_with_http_info(self, barcode_type, data_type, data, **kwargs):
        """Generate barcode using POST request with parameters in url ecncoded form.

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = GenerateApi().barcode_generate_form_post_with_http_info(barcode_type, data_type, data, async_req=True)
        >>> result = thread.get()

        :param EncodeBarcodeType barcode_type: # noqa: E501
        :param EncodeDataType data_type: # noqa: E501
        :param str data: String represents data to encode # noqa: E501
        :return: bytearray
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = {
            "barcode_type",
            "data_type",
            "data",
            "image_format",
            "two_d_display_text",
            "text_location",
            "text_alignment",
            "foreground_color",
            "background_color",
            "units",
            "resolution",
            "image_height",
            "image_width",
            "rotation_angle",
        }
        all_params.add("async_req")
        all_params.add("_return_http_data_only")
        all_params.add("_preload_content")
        all_params.add("_request_timeout")

        params = locals()
        for key, val in params["kwargs"].items():
            if key not in all_params:
                raise TypeError("Got an unexpected keyword argument '%s'" " to method barcode_generate_form_post" % key)
            if val is None:
                continue

            params[key] = val
        del params["kwargs"]
        # verify the required parameter "barcode_type" is set
        if "barcode_type" not in params or params["barcode_type"] is None:
            raise ValueError("Missing the required parameter 'barcode_type' when calling 'barcode_generate_form_post'")
        # verify the required parameter "data_type" is set
        if "data_type" not in params or params["data_type"] is None:
            raise ValueError("Missing the required parameter 'data_type' when calling 'barcode_generate_form_post'")
        # verify the required parameter "data" is set
        if "data" not in params or params["data"] is None:
            raise ValueError("Missing the required parameter 'data' when calling 'barcode_generate_form_post'")

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}
        if "barcode_type" in params:
            form_params.append(("barcodeType", params["barcode_type"]))
        if "data_type" in params:
            form_params.append(("DataType", params["data_type"]))
        if "data" in params:
            form_params.append(("Data", params["data"]))
        if "image_format" in params:
            form_params.append(("ImageFormat", params["image_format"]))
        if "two_d_display_text" in params:
            form_params.append(("TwoDDisplayText", params["two_d_display_text"]))
        if "text_location" in params:
            form_params.append(("TextLocation", params["text_location"]))
        if "text_alignment" in params:
            form_params.append(("TextAlignment", params["text_alignment"]))
        if "foreground_color" in params:
            form_params.append(("ForegroundColor", params["foreground_color"]))
        if "background_color" in params:
            form_params.append(("BackgroundColor", params["background_color"]))
        if "units" in params:
            form_params.append(("Units", params["units"]))
        if "resolution" in params:
            form_params.append(("Resolution", params["resolution"]))
        if "image_height" in params:
            form_params.append(("ImageHeight", params["image_height"]))
        if "image_width" in params:
            form_params.append(("ImageWidth", params["image_width"]))
        if "rotation_angle" in params:
            form_params.append(("RotationAngle", params["rotation_angle"]))

        body_params = None
        # HTTP header "Accept"
        header_params["Accept"] = self.api_client.select_header_accept(
            [
                "image/png",
                "image/bmp",
                "image/gif",
                "image/jpeg",
                "image/svg+xml",
                "image/tiff",
                "application/json",
                "application/xml",
            ]
        )

        # HTTP header "Content-Type"
        header_params["Content-Type"] = self.api_client.select_header_content_type(
            ["application/x-www-form-urlencoded"]
        )

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(
            "/barcode/generate-form",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="bytearray",
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", False),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )
