# coding: utf-8

"""

    Copyright (c) 2020 Aspose.BarCode for Cloud

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

"""


import pprint
import re  # noqa: F401

import six


class QRVersion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AUTO = "Auto"
    VERSION01 = "Version01"
    VERSION02 = "Version02"
    VERSION03 = "Version03"
    VERSION04 = "Version04"
    VERSION05 = "Version05"
    VERSION06 = "Version06"
    VERSION07 = "Version07"
    VERSION08 = "Version08"
    VERSION09 = "Version09"
    VERSION10 = "Version10"
    VERSION11 = "Version11"
    VERSION12 = "Version12"
    VERSION13 = "Version13"
    VERSION14 = "Version14"
    VERSION15 = "Version15"
    VERSION16 = "Version16"
    VERSION17 = "Version17"
    VERSION18 = "Version18"
    VERSION19 = "Version19"
    VERSION20 = "Version20"
    VERSION21 = "Version21"
    VERSION22 = "Version22"
    VERSION23 = "Version23"
    VERSION24 = "Version24"
    VERSION25 = "Version25"
    VERSION26 = "Version26"
    VERSION27 = "Version27"
    VERSION28 = "Version28"
    VERSION29 = "Version29"
    VERSION30 = "Version30"
    VERSION31 = "Version31"
    VERSION32 = "Version32"
    VERSION33 = "Version33"
    VERSION34 = "Version34"
    VERSION35 = "Version35"
    VERSION36 = "Version36"
    VERSION37 = "Version37"
    VERSION38 = "Version38"
    VERSION39 = "Version39"
    VERSION40 = "Version40"
    VERSIONM1 = "VersionM1"
    VERSIONM2 = "VersionM2"
    VERSIONM3 = "VersionM3"
    VERSIONM4 = "VersionM4"

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {}

    attribute_map = {}

    def __init__(self):  # noqa: E501
        """QRVersion - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], "to_dict") else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(QRVersion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QRVersion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
