name: Check badges in README.md

on:
  push:
    branches: [ v3 ]
  pull_request:
    branches: [ v3 ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check badges in README.md
      run: ./scripts/check-badges.bash "README.md"
