name: Latest Python

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python on ${{ matrix.operating-system }}
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install -r test-requirements.txt
    - name: Lint
      run: |
        python -m black --line-length=120 --check .
        python -m check_python_versions --expect 2.7,3.5- --only setup.py
    - name: Test
      env:
        TEST_CONFIGURATION_ACCESS_TOKEN: ${{ secrets.TEST_CONFIGURATION_ACCESS_TOKEN }}
      run: python -Werror -m pytest
