name: Latest Python Support

on:
  push:
    branches: [ v3 ]
  pull_request:
    branches: [ v3 ]

jobs:
  # Define the job to run before your matrix job
  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      python-matrix: ${{ steps.get-python-versions-action.outputs.latest-python-versions }}
    steps:
    - uses: snok/latest-python-versions@v1
      id: get-python-versions-action
      with:
        min-version: '3.13'

  test:
    needs: [get-python-versions]
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macOS-latest ]
        python-version: ${{ fromJson(needs.get-python-versions.outputs.python-matrix) }}

    continue-on-error: true

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python on ${{ matrix.operating-system }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt -r test-requirements.txt
    - name: Lint
      run: |
        python -m black --line-length=120 --check .
        python -m check_python_versions --expect 3.8- --only setup.py
    - name: Test
      env:
        TEST_CONFIGURATION_ACCESS_TOKEN: ${{ secrets.TEST_CONFIGURATION_ACCESS_TOKEN }}
      run: python -Werror -m pytest
