name: Check Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  twine-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.x'

    - name: Set up Requirements
      run: python -m pip install -r publish-requirements.txt
    - name: Build dist
      run: python setup.py sdist bdist_wheel --universal
    - name: Check
      run: python -m twine check dist/* --strict
